#!/usr/bin/env bash

echo "======================================"
echo "锄大D计分器 Android 项目"
echo "======================================"
echo ""
echo "📁 项目目录: $(cd "$(dirname "$0")" && pwd)"
echo ""
echo "✅ 核心实现："
echo "  - Java 计分逻辑（GameSession, Player, Round）"
echo "  - 大陆锄大地计分：剩余牌数折算牌分 + 全场零和"
echo "  - Android Activity 和 UI 布局"
echo "  - AndroidManifest.xml 配置"
echo "  - Gradle 构建配置"
echo "  - 单元测试（GameSessionTest）"
echo ""
echo "🚀 功能特性："
echo "  ✓ 4人游戏计分"
echo "  ✓ 逐局输入每人剩余牌数，自动判定赢家"
echo "  ✓ 实时排名显示（正分绿色，负分红色）"
echo "  ✓ 逐局历史记录"
echo "  ✓ 新游戏重置"
echo "  ✓ 完全离线运行，无需 Google Play 服务"
echo ""
echo "📦 命令行构建与测试："
echo "   ./gradlew assembleDebug   # 构建 Debug APK"
echo "   ./gradlew test            # 运行单元测试"
echo ""
echo "======================================"

# List project structure
echo "📂 项目文件列表："
echo ""
find "$(cd "$(dirname "$0")" && pwd)" -type f \( -name "*.java" -o -name "*.xml" -o -name "*.gradle" \) -not -path "*/.git/*" | sort
echo ""
echo "======================================"
echo "✨ 完成"
echo "======================================"